(PUP-5938) Fix localized WinNT BUILTIN monikers
 - When building WinNT monikers, BUILTIN and NT AUTHORITY cannot be
   used to refer to users / groups and those names must be replaced
   with "."  For instance, SYSTEM account must use the moniker:

   WinNT://./SYSTEM,user - NOT WinNT://NT AUTHORITY/SYSTEM,user

   455834e7f21f213e9d0085510d5b47c0c3e2a1ab added the initial code for
   User moniker generation to take that into account

   Similarly, a group moniker for Administrators should use:

   WinNT://./Administrators,group - NOT WinNT://BUILTIN/Administrators,group

   bd3f3a18fa4b5ae1f1f26d8aabf74edd18598746 made sure that monikers
   for groups followed this behavior correctly as well.

   NOTE: These monikers are used only for adding / removing users to
   groups, or groups to a user - and aren't always able to be used
   with WIN32OLE.connect - this is an instrinsic behavior of the
   WinNT:// provider.

 - That code remained partially dormant, until other bugs were resolved
   for PUP-5684 in 7e176bfb3adf53d234d893f8481f576e3a2e6a0b and user
   User / Group began to more actively use the WinNT monikers in the
   exists? checks

 - On non-US versions of Windows, the "domains" BUILTIN and
   NT AUTHORITY may be localized.  For instance, on German Windows
   BUILTIN is localized as VORDEFINIERT and NT AUTHORITY is localized
   as NT-AUTORITÄ.  On French Windows, NT AUTHORITY is localized
   as AUTORITE NT, but BUILTIN remains the same.

   The moniker construction code has never taken this into account
   previously, so when trying to add a User to the Administrators
   group in German Windows, this would fail (this issue in particular
   was likely introduced in bd3f3a18fa4b5ae1f1f26d8aabf74edd18598746):

   Given a manifest:

   user { 'bla':
    ensure  => 'present',
    comment => 'bla',
    groups  => ['S-1-5-32-544',],
   }

   Would generate:

   Error: ADSI connection error: failed to parse display name of moniker `WinNT://VORDEFINIERT/Administratoren,group'
       HRESULT error code:0x80070035
         Der Netzwerkpfad wurde nicht gefunden.