(#6936) Fix undefined method "groupname_by_id" error on AIX user provider
Without this patch, `puppet resource user lindsey gid=4242 ensure=present` fails with the following error:

`err: /User[lindsey]/gid: change from 600 to 4242 failed: undefined method 'groupname_by_id' for #<Puppet::Type::User::ProviderAix:0x20eae6e0>`

This patch fixes the problem by fixing the method definition which makes the above command succeed:

`notice: /User[lindsey]/gid: gid changed '600' to '4242'`