(PUP-4814) Use ENV variables in the path of scheduled tasks folder.
- The system drive doesn't have to be C:
- If a Windows Server 2003 system is upgraded from Windows 2000 or NT,
  the default %SYSTEMROOT% or %WINDIR% is C:\WINNT rather than
  C:\Windows

So if hardcoded the path of scheduled tasks folder as
C:\Windows\Tasks, the following error might occur:

Error: /Stage[main]/test/Scheduled_task[foo]: Could not evaluate: No such file or directory @ dir_initialize - C:/Windows/Tasks