(PUP-10324) Refine how content-length is set
Puppetserver's Apache HttpClient raises an exception if the `Content-Length`
header is set in POST requests, so remove that from the external client:

    org.apache.http.ProtocolException: Content-Length header already present

When using Puppet::HTTP::Client, set the content length directly using
`content_length=` instead of indirectly via the header[1]. It's mostly the same
except it ensures the header value is a string (as it should be) and not an
integer.

[1] https://github.com/ruby/ruby/blob/v2_5_7/lib/net/http/header.rb#L315-L321