(PUP-5707) Fail the file resource if the checksum type is unknown
Previously, if an unknown checksum type was specified for a file resource, then
a NoMethodError was raised, which causes the entire catalog run to fail:

    Error: undefined method `rot13?' for #<Puppet::Type::File:0x00007f80f3a147a0>

Now gracefully handle the unknown checksum type so that the failure message
prints which resource failed and its location info (file & line):

    Error: Validation of File[/tmp/rpm-gpg-key] failed: Checksum value ...
    is not a valid checksum type rot13 (line: 1)