(PUP-7880) Ensure log message attributes are UTF-8
 - Log message objects contain attributes other than the string
   message itself, which may be concatenated to form the actual string
   to write when the handle method of each instance of
   Puppet::Util::Log::Destination is executed.

   For instance, the :console destination and :file destination may
   concatenate the @source and @message of a Log message.

 - While Puppet began coercing log messages to UTF-8 as part of
   c47be2d3b3d002f02cbed6edee8dfee119152b46 it didn't also coerce the
   source.

   In many circumstances, Ruby is happy to concatenate UTF-8 strings
   with strings of other encodings that only use 7-bit ASCII characters
   that are consistent amongst all encodings.

   However, it is also possible under certain circumstances to
   generate a @source and @message that are of different encodings
   that cannot be concatenated.

   In such cases, attempts to log will result in Puppet crashing with
   an error like:

   Error: Failed to apply catalog: incompatible character encodings: IBM437 and UTF-8

 - Such a failure occurs when running the following manifest through
   Cygwin:

     file { "c:/temp":
       ensure => directory
     }

     file { "c:/temp/unicode_dir_ㅀㅅㅶㅅㅲㅂㅄㅉㅑㅧㅩㅙㅘ":
       ensure  => directory,
       require => File['c:/temp']
     }

     user { "bob":
       ensure     => present,
       groups     => 'Users',
       managehome => true,
       password   => "L0v3Pupp3t!"
     }

     acl { "c:/temp/unicode_dir_ㅀㅅㅶㅅㅲㅂㅄㅉㅑㅧㅩㅙㅘ":
       permissions => [
         { identity => 'bob', rights => ['full']  },
       ],
     }

 - Log destinations *should* have already had their messages groomed
   so that both the @source and @message attributes are uniformly
   in UTF-8, so that specific log implementations like :console and
   :file don't have to be aware of any additional string coercing
   behavior.

 - Add tests demonstrating the problem, noting that the :console
   log destination is being used specifically as it has special
   behavior when calling `handle` for generating actual messages.