(PUP-5538) Support non-US langs for User / Group
 - Previously, Puppet relied on the win32/security gem and the
   Win32::Security::SID class to resolve SIDs and account names.
   However, that gem does not properly support wide character
   strings (UTF-16LE) by using the wide versions of Windows API calls.
   This prevents Puppet from properly managing user names that contain
   Unicode characters, for instance the German administrators group
   which contains an ä.

   Applying the manifest (even with codepage set to 65001):

   user { 'german':
     ensure => present,
     groups => ['GroupwithUmlautä'],
   }

   Used to produce an error like:

   Error: Could not resolve name: GroupwithUmlautä
   Error: /Stage[main]/Main/User[german]/ensure: change from absent to present failed: Could not resolve name: GroupwithUmlautä

   This is no longer the case when codepage is set to 65001 (but may
   still be the case with other codepages do to separate issues).

   When attempting to workaround these other issues by using the SID
   of the group instead of the name with a manifest like:

   user { 'german':
     ensure => present,
     groups => ['S-1-5-21-271343509-1886877197-423808128-3799'],
   }

   The first run would succeed and place the user in the group, but the
   second run would fail with an error like:

   Error: Failed to apply catalog: Could not resolve name: GroupwithUmlautä

   This workaround now behaves properly, regardless of the codepage
   currently set.  This provides a way for users of German windows to
   add accounts to the local Administrators group with its well-known
   SID S-1-5-32-544 like:

   user { 'german':
     ensure => present,
     groups => ['S-1-5-32-544'],
   }

 - To correct this behavior internally, implement LookupAccountSidW,
   LookupAccountNameW and rewrite the SID related functions to behave
   properly with Unicode strings.

   Introduce a lightweight class Puppet::Util::Windows::SID::Principal
   that mirrors the previous interface where appropriate, for the sake
   of backward compatibility.

   Change tests that relied on the previous to_s behavior of the
   Win32::Security::SID class to instead use the .sid member.  The to_s
   method is added back in the next commit for the sake of backwards
   compatibility.  Similarly, implement an == function that compares
   SID::Principal instances by their SID string.