(PUP-9312) Fix errant registry read message
 - When failing to retrieve a registry value, the API called to read
   the pointer of the name of the subkey was used improperly,
   resulting in a messsage like:

   Error: Could not run: wrong number of arguments (given 0, expected 1..3)
   C:/source/puppet-PUP-9312/lib/puppet/util/windows/api_types.rb:56:in `read_wide_string'

   Fix this, so the message is correctly emitted instead like:

   Error: Could not run: Failed to read registry value QuietDisplayName at Software\Microsoft\Windows\CurrentVersion\Uninstall\7-Zip:  The operation completed successfully.