(maint) Update rubygems and remove unnecessary step
This commit updates rubygems to latest version to avoid the following
error: ``` Your RubyGems version (2.5.2.3)) has a bug that prevents
`required_ruby_version` from working for Bundler. Any scripts that use
`gem install bundler` will break as soon as Bundler drops support for
your Ruby version. Please upgrade RubyGems...  ```

This commit also removes an unnecessary step that installed `bundler` a
second time since the `ruby/setup-ruby@v1` action now also installs
bundler.

(cherry picked from commit 8f9992704fc353d5639108bd63761b1736d4d3d2)

Removed `--silent` argument as it's not supported in all rubygem versions