(PUP-2505) Puppet HTTP API, certificate_status, DELETE request broken Duplicates:    PUP-2483 Deleting a certificate does not work with the API    PUP-2516 Delete a clients certificate with HTTP API no longer working
HTTP API requests using the DELETE method are failing with "Server Error:
undefined method `each' for nil:NilClass"...

e.g.
 curl -k -X DELETE https://${PMASTER}:8140/production/certificate_status/$AGENT

Traced problem back to missing specification for :DELETE in @method_handlers