(#11331) Allow parenthesized expressions in ifs
The construction
  if ($var) { ... }
resulted in an error during parsing. The error was
  Error: nil can't be coerced into Fixnum at ...
This was caused by a parenthesized expression not retaining any location
information. The grammar needs to retain the location information for
the resulting model.