(maint) Change spec test to pass on ruby 2.2
Prior to this change, this spec test failed on ruby 2.2.0-rc1 with:

     Failure/Error: Time.stubs(:now).returns(Time.parse("2011-01-06 12:00:00 UTC"))
     NoMethodError:
       undefined method `utc_offset' for nil:NilClass

I didn't track down the root cause of this failure, but just
normalized this stub to use Time.utc, which (along with Time.local)
is the more common way of stubbing Time objects in the codebase.