(PUP-5591) Fix registry binary read
Previously, the read method was using an older variable name when
reading data for binary values. It would result in errors such as the
following when reading a binary value from the registry.

~~~
Error: Could not run: undefined local variable or method `data' for
Puppet::Provider::Package::Windows::Package:Class
C:/Program Files/Puppet
Labs/Puppet/puppet/lib/puppet/util/windows/registry.rb:216:in `block in
read'
~~~

This was introduced in b46ede74f640a809b68a473ac8720b93b13d2ac3 (Puppet
v4.0.0).

Without this fix, any registry enumerations that contain a binary
value will fail.