(PUP-9825) Raise if the user or group provider is not suitable
If user/group providers were not suitable and puppet tried to manage its
internal file-related settings, then puppet printed a cryptic error:

    Could not create resources for managing Puppet's files and directories in
    sections [:main, :agent, :ssl]: undefined method `exists?' for nil:NilClass

Now we raise if the user or group provider is not functional. It's not a
breaking change, since we raised previously too.