(PUP-3821) Don't check Windows admin? with Facter
 - The previous method for checking whether a user is an admin? on
   Windows can cause issues loading Puppet when the --cfacter switch is
   applied.  The error message is:

   Error: Could not initialize global default settings: facter has
   already evaluated facts.

   Detect that the Windows major version is at least 6 (Vista+) as a
   shortcut to whether or not TokenElevation is available on the current
   operating system.

   An alternative approach would rewrite supports_elevated_security to
   execute similarly to elevated_security?, but watch only for
   ERROR_NO_SUCH_PRIVILEGE.  This would be less code, but several
   additional API calls to clone the current process token and
   call GetTokenInformation against it.