(PUP-9997) Remove dead code
The Puppet::Util::Reference.pdf method has been broken since 2012 due to
commit f0c99956e7e3dcd68bdec570cbc32adf88b53163, because it was calling
Puppet::Util.replace_file with 1 argumentm, but it takes 2, resulting
in:

    $ puppet doc --mode pdf --reference type
    creating pdf
    Error: Could not run: wrong number of arguments (given 1, expected 2)

So delete the code and remove `pdf` as a valid reference doc mode.