(PUP-2298) Use resource specific log_exception
Previously, we were logging the exception using `Puppet.err` and
passing in the resource reference in the message.

This commit changes it to use the log_exception method mixed into the
resource (Puppet::Type) so that we get resource-specific error
messages.

    Error: /Stage[main]/Main/Notify[hello]: something is not right