(PUP-9586) Preserve error showing callback failed
Preserve the original behavior of emitting an error message that the
callback failed, followed by the exception that caused the issue:

    Error: /Stage[main]/Main/Exec[exec]: Failed to call refresh: '/usr/bin/false' returned 1 instead of one of [0]
    Error: /Stage[main]/Main/Exec[exec]: '/usr/bin/false' returned 1 instead of one of [0]`