(PUP-6499) Ensure WIN32OLE objects emit UTF-8
 - When retrieving the names of users / groups and their attributes
   through WMI, Ruby will unfortunately convert any returned strings
   into the local codepage (Default.external_encoding) instead of
   converting the values from UTF-16LE to UTF-8 for internal
   consumption.

   This then causes problems with Puppets logging when attempting to
   combine strings that are in UTF-8 and the local encoding.  This was
   observed on French Windows where the default encoding is CP850.

   Without these changes `puppet resource user` will fail to run with
   the error:

Error: Could not run: incompatible character encodings: UTF-8 and CP850

 - Add some tests demonstrating the encoding is set appropriately in
   the results returned from the ADSI provider. Note that the tests
   temporarily set a different codepage (it doesn't particularly
   matter what is selected), prior to making the COM calls via Ruby.

 - Note that the [] attribute reader on User is re-encoding string
   values returned by IAdsUser.Get (that Ruby has encoded in the
   local codepage).  It's assumed that callers of []= are already
   supplying UTF-8 strings for the attribute name and value where
   appropriate (and Ruby should be translating these to UTF-16LE to
   call the real APIs) and thus no conversions are necessary here.