(#18494) Make ActiveRecord-based inventory service unsupported under Ruby 2
ActiveRecord 3.0 under Ruby 2.0 has spec failures both here and upstream, and
isn't supported anyhow.  Disable the ActiveRecord-based inventory service when
running under Ruby 2.

  2) Puppet::Node::Facts::InventoryActiveRecord#save should retry on ActiveRecord error
     Failure/Error: Puppet::Node::Facts.indirection.save(facts)
     NoMethodError:
       undefined method `insert_record' for #<Array:0x0000001950d3b8>
     # ./lib/puppet/indirector/facts/inventory_active_record.rb:40:in `block (2 levels) in save'
     # ./lib/puppet/indirector/facts/inventory_active_record.rb:32:in `block in save'
     # ./lib/puppet/util/retryaction.rb:21:in `retry_action'
     # ./lib/puppet/indirector/facts/inventory_active_record.rb:27:in `save'
     # ./lib/puppet/indirector/indirection.rb:266:in `save'
     # ./lib/puppet/node/facts.rb:20:in `save'
     # ./spec/unit/indirector/facts/inventory_active_record_spec.rb:43:in `block (3 levels) in <top (required)>'