(maint) Clarify the error message when a relationship can't be established
The following error message:

    Error: Could not retrieve catalog from remote server: Could not intern
    from text/pson: Could not intern from data: Could not find relationship
    target "File[]"

Will get additional information:

    Error: Could not retrieve catalog from remote server: Could not intern
    from text/pson: Could not intern from data: Could not find relationship
    target "File[]" for Apache::Vhost[example.com]

So the error is easier to debug.