(maint) Pidlock#file_path uses correct instance var
Typo in Puppet::Util::Pidlock#file_path was referencing @lock_data which
doesn't exist.  This was resulting in messages like:

"Could not prepare for execution: undefined method `file_path' for
nil:NilClass"

instead of the slightly less confusing:

"Could not prepare for execution: Could not create PID file:
/home/jpartlow/.puppet/var/run/agent.pid"

From lib/puppet/daemon.rb:157 when attempting a second 'puppet agent'
call with existing daemonized agent.