(PUP-9176) List failed module install dependencies
Depends on https://github.com/puppetlabs/semantic_puppet/pull/34.

The changes are backwards compatible so they shouldn't break users with
older versions of semantic_puppet.

Fixed a bug where we wouldn't print the version of the module we're
installing when raising this specific error.

Also, when installing a module without specifying its version, the error
message will show the best candidate instead of `(???)`.

Before (assuming puppetlabs-concat 6.4.0 is installed prior to this):

```
Error: Could not install module 'trepasi-debnet' (???)
  No version of 'trepasi-debnet' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

After:

```
Error: Could not install module 'trepasi-debnet' (v1.5.2)
  The requested version cannot satisfy the following dependency: puppetlabs-concat
    Installed: 6.4.0, expected: >= 1.2.0 < 3.0.0
    Use `puppet module install 'trepasi-debnet' --ignore-dependencies` to install only this module
```

Co-authored-by: Luchian Nemes <luchian.nemes@puppet.com>