(PUP-10604) Guard against JRuby FIPS
Puppetserver still loads all types and providers during catalog compilation,
and JRuby with FIPS enabled cannot require rubygems. So guard the require
statement like we do in puppet/ssl/openssl_loader.

The `/opt/puppetlabs/bin/puppetserver gem install` command will fail
when running with JRuby with FIPS, so confine the provider when
`fips_enabled` is false. That way trying to manage a puppetserver gem
will print:

    Error: /Stage[main]/Main/Package[uuid]: Provider puppetserver_gem is not functional on this host

instead of:

    Error: Execution of '/opt/puppetlabs/bin/puppetserver gem install --no-document <gem>' returned 1:
      ERROR:  Loading command: install (NameError)
      cannot load (ext) (org.jruby.ext.openssl.OpenSSL)