(PUP-4373) Windows User resource groups - use SIDs
Previously, when specifying a user's groups, the names were compared
as strings and needed to be an exact match. The group resource uses
SIDs when comparing the users, so the user resource should mimic that
behavior.

Implement the comparison and setting functionality when setting
groups. Without this change, setting user groups will continue to be
naive and incorrect.

Prior to this commit, applying the manifest succeeds:

user { 'tim':
  ensure               => present,
  groups               => ['BUILTIN\Administrators'],
}

However, then applying the manifest:

user { 'tim':
  ensure               => present,
  groups               => ['BUILTIN\Administrators', 'Users'],
}

Would generate the error:

Error: (in OLE method `Add': )
    OLE error code:80070562 in Active Directory
      The specified account name is already a member of the group.

    HRESULT error code:0x80020009
      Exception occurred.
Error: /Stage[main]/Main/User[jim]/groups: change from Administrators to Administrators,BUILTIN\Administrators,Users failed: (in OLE method `Add': )
    OLE error code:80070562 in Active Directory
      The specified account name is already a member of the group.

    HRESULT error code:0x80020009
      Exception occurred.