(PUP-6802) Fallback to default environment when given is missing
When an agent runs with a environment that does not exist on the server,
puppet will fail with
```
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Find /puppet/v3/node/steep-ribcage.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'qwe'","issue_kind":"RUNTIME_ERROR"}
Info: Retrieving pluginfacts
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment qwe source(s) puppet:///pluginfacts
Info: Retrieving plugin
Error: /File[/opt/puppetlabs/puppet/cache/lib]: Could not evaluate: Could not retrieve information from environment qwe source(s) puppet:///plugins
Info: Retrieving locales
Error: /File[/opt/puppetlabs/puppet/cache/locales]: Could not evaluate: Could not retrieve information from environment qwe source(s) puppet:///locales
Error: Could not retrieve catalog from remote server: Find /puppet/v3/catalog/steep-ribcage.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'qwe'","issue_kind":"RUNTIME_ERROR"}
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Now in case it cannot get the facts or catalog for the specified
environment, it will fallback to the environment configured in the
new default_agent_environment puppet setting.