(PUP-7516) Fix Fedora25 createrepo failures
 - On 5/3/2017 version 7.43.0-5.fc25 of python-pycurl was released to
   address issue https://bugzilla.redhat.com/show_bug.cgi?id=1446850

   ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (nss)

 - Puppet performs some package tests with yum and dnf providers by
   installing / using createrepo.  Createrepo requires python and a
   number of python dependencies, including the python-pycurl bindings
   for curl.  These bindings depend on the curl package.

   Unfortunately on Fedora 25, the baseline curl package installed on
   images is curl-7.50.3-1.fc25.x86_64. This curl package in
   conjunction with the newer python-pycurl 7.43.0-5.fc25 will
   generate an error when calling createrepo:

   ImportError: pycurl: libcurl link-time version (7.50.3) is older than compile-time version (7.51.0)

 - One solution to this problem is to downgrade the python-pycurl
   package to the older working version with:

   yum downgrade python-pycurl-7.43.0-4.fc25

 - Another solution would be to not mirror the newer package.

 - Given both of these options are brittle, it's been decided that
   when installing createrepo, curl should be upgraded at the same
   time. In testing, the newer curl 7.51.0-6.fc25 has been found to
   be compatible with the updated python-pycurl, allowing createrepo
   to function again without crashing.

 - To be able to upgrade curl, which may already be installed on a
   target machine, requires that the `--best` parameter be passed
   to yum / dnf install (both package managers have the feature). It
   also requires memoizing whether or not the package has been
   previously installed in Puppet::Acceptance::RpmUtils#setup_rpm.
   That method currently checked if a package was installed and would
   skip installing it if it was already present. Since that prevents a
   desireable upgrade of curl, make it track whether or not an install
   / upgrade has been attempted.

   8c1751ed96e094608f98578b95078e577cc07e72 defined the original setup
   method which is modified here