(PUP-6494) Support sensitive commands in Exec resource type.
This commit adds support for sensitive commands in the `Exec` resource type:
`command` parameters that are specified as `Sensitive.new(...)` are now
properly redacted when the command fails.  This supports using data from lookup
and hiera.

Example:
```puppet
exec { 'redacted':
  command => Sensitive.new('/usr/bin/false SECRET_TEXT')
}
```

Output:
```
Error: [command redacted] returned 1 instead of one of [0]
Error: /Stage[main]/Main/Exec[redacted]/returns: change from notrun to 0 failed:
[command redacted] returned 1 instead of one of [0]
```