Revert "Merge pull request #1682 from zaphod42/issue/master/incorrect-management-of-rundir"
This reverts commit a6e746d1a5df96f59ea0fdbe13345a5fcdacc7ff, reversing
changes made to 4cce551e419c57fb1306fa4b98a429f83aa2527a.

This appears to be causing inexplicable failures in some testing
machines. The errors manifest with the master being unable to write to
certain directories:

  Warning: Unable to fetch my node definition, but the agent run will continue:
  Warning: Error 400 on SERVER: cannot generate tempfile `/var/lib/puppet/yaml/node/solaris-11-32-2.delivery.puppetlabs.net.yaml20130606-4478-it4k80-9'
  Info: Retrieving plugin
  Error: /File[/var/lib/puppet/lib]: Could not evaluate: Could not retrieve information from environment production source(s) puppet://solaris-11-32-2/plugins
  Error: Could not retrieve catalog from remote server: Error 400 on SERVER: cannot generate tempfile `/var/lib/puppet/yaml/facts/solaris-11-32-2.delivery.puppetlabs.net.yaml20130606-4478-19pqoux-9'
  Warning: Not using cache on failed catalog
  Error: Could not retrieve catalog; skipping run