(PUP-10040) Print resolution exceptions when routing fails
Previously, if an agent couldn't connect to the CA to bootstrap its SSL certs,
it only printed "No more routes to ca" while the actual connection failure was
logged at :debug level. This caused the windows eventlog acceptance test to
fail, since "puppet agent -t" sets the log level to :info, preventing the
expected message from being logged.

This commit continues to log each individual connection failures at debug as is
done in Puppet::Configurer#find_functional_server and Puppet::Rest::Routes when
using SRV records, but if we exhaust all resolvers, then we log each exception
at error level, and raise the "no more routes" error as we did before:

    C:\> puppet agent -t
    ...
    Error: Failed to connect to https://127.0.0.1:8140/puppet-ca/v1: Failed to open TCP connection to 127.0.0.1:8140 (Connection refused - connect(2) for "127.0.0.1" port 8140)
    Wrapped exception:
    Failed to open TCP connection to 127.0.0.1:8140 (Connection refused - connect(2) for "127.0.0.1" port 8140)
    Error: No more routes to ca
    Error: Could not run: No more routes to ca