(maint) Match Bolt executor run_script signature
 - While the Puppet run_script function should later be updated to
   include passing arguments, for now we can pass an emtpy arguments
   array for the sake of being able to properly call Bolt.

   As it stands, without this change, users attempting to use
   run_script in plans like the following:

   plan sample::script_test(String $nodes) {
     run_script(split($nodes, ','), "sample/uploads/test.ps1")
   }

   Will receive an error like:

   Error: Evaluation Error: Error while evaluating a Function Call, wrong number of arguments (given 2, expected 3) at /Users/Iristyle/source/bolt/spec/fixtures/modules/sample/plans/script_test.pp:2:3 on node niihau.delivery.puppetlabs.net