(PUP-2838) Add unit test to demonstrate the problem
This change introduce a few failing unit tests related to quotes esaping
in dot graph generation.

Puppetlabs's postgresql module produce a lot of resources named this
way, making graph generation failing with a message similar to:

Error: /var/puppet/state/graphs/relationships.dot: syntax error in line 5765 near '"'