(PUP-4373) Windows User groups_insync? Compare SID
Use SIDS when comparing user groups. Implement similar behavior as
Group members when comparing whether the groups a user is in are in
sync with current. Without this change casing and names must match
exactly and can produce erroneous results.

With this change, the comparison will be by SIDs, and applying
this manifest multiple times works correctly:

user { 'tim':
  ensure => present,
  groups => ['users'],
}

Would generate an error because 'users' did not match 'Users':

Error: (in OLE method `Add': )
    OLE error code:80070562 in Active Directory
      The specified account name is already a member of the group.

    HRESULT error code:0x80020009
      Exception occurred.
Error: /Stage[main]/Main/User[tim]/groups: change from Users to Users,users failed: (in OLE method `Add': )
    OLE error code:80070562 in Active Directory
      The specified account name is already a member of the group.

    HRESULT error code:0x80020009
      Exception occurred.

Furthermore, a group name like BUILTIN\ in the manifest:

user { 'tim':
  ensure               => present,
  groups               => ['BUILTIN\Administrators'],
}

Would generate the following error:

Error: ADSI connection error: failed to parse display name of moniker `WinNT://./BUILTIN\Administrators,group'
    HRESULT error code:0x800708ac
      The group name could not be found.
Wrapped exception:
failed to parse display name of moniker `WinNT://./BUILTIN\Administrators,group'
    HRESULT error code:0x800708ac
      The group name could not be found.
Error: /Stage[main]/Main/User[jim]/ensure: change from absent to present failed: ADSI connection error: failed to parse display name of moniker `WinNT://./BUILTIN\Administrators,group'
    HRESULT error code:0x800708ac
      The group name could not be found.