Change hiera_include to properly call include with an array of arguments
Before this change hiera includes which looked up an empty array
resulted in this error:

    ArgumentError: include(): Wrong number of arguments given (0 for minimum 1)

Now hiera includes properly allow for a lookup that results in an empty
array

This regression was caused by the arity checks committed in
9ed6fcea48591cda58db1379b58cd39dfbdca684