(PUP-9926) Fix autorelations build for puppet types
Reverted form `Array(list)` to [list] introduced in: https://github.com/puppetlabs/puppet/commit/6c257fc7827989c2af2901f974666f0f23611153#diff-7f00f7dbc0f9bfecbaadfec966d0b8b1L2149

Creating an object with `Array(object)` will be using the `Array()` method,
provided by `Kernel`, which tries to call `to_ary`, then `to_a` on its argument.
`to_ary` allows an object to be treaten as an array and then it will call
`to_a` on that object.

If you pass in an object that is an instance of a class
which includes the `Enumerable` module, it will try to call `to_a`
from the implementation of `Enumerable` which will result in an error:
`NoMethodError (undefined method 'each' for #<A:0x00007ffa50859088>)`

```
class A
  include Enumerable
end

2.5.5 > A.new.method(:to_a)
 => #<Method: A(Enumerable)#to_a>
 ```

Documentation:
- https://docs.ruby-lang.org/en/2.4.0/Array.html#method-i-to_ary
- https://docs.ruby-lang.org/en/2.4.0/Array.html#method-i-to_a
- https://docs.ruby-lang.org/en/2.4.0/Enumerable.html#method-i-to_a