(PUP-7772) Ensure string msg in ExecutionFailure
 - Puppet::ExecutionFailure is derived from Puppet::Error, which in
   future versions of Puppet (5.0.0+) performs additional scrubbing of
   passed strings to ensure that they match the output encoding.

   In that future case, the behavior of the initializer is subtly
   different from the current code:

   def initialize(message, original=nil)
     super(message)
     @original = original
   end

   Calling super directly in the current code will call RuntimeError
   within Ruby, which despite the Ruby documentation, will implicitly
   call .to_s on the second parameter, which is always intended to be
   a string.  That means that Ruby allows things like:

   [1] pry(main)> raise RuntimeError, 2
   RuntimeError: 2

   [2] pry(main)> raise RuntimeError, ['foo']
   RuntimeError: ["foo"]

   [3] pry(main)> raise RuntimeError, StringIO.new('hi')
   RuntimeError: #<StringIO:0x007fdb040d4ee0>

 - #execpipe currently raises an IO object which RuntimeError is
   conveniently / implicitly calling .to_s against.

   In Puppet 5, the initializer changes to

   def initialize(message, original=nil)
     super(Puppet::Util::CharacterEncoding.scrub(message))
     @original = original
   end

   In this case, when message is an IO object - the code crashes
   instead of implicitly calling .to_s and then performing the scrub.

 - Code is targeted at this older version as it's a very minor change
   and is a preventive measure in the event that any of the encoding
   scrubbing changes are backported to the LTS release based on
   customer demand.