(maint) Attach pe classifier groups to Production environment group
Runs of PE Puppet Acceptance for 3.8.x began failing several environment
tests after the new "Production environment" group was added to the
default pe classifications in PE-8444.  This new "Production
environment" group set the production environment for all pe nodes.  The
failing environment tests were making us of the helper method
lib/puppet/acceptance/classifier_utils#create_group_for_nodes to
create test groups in the classifier setting environment for nodes
under test.  But the method was setting the parent to the default root
group, and this was causing the classifier to return a conflict error
due to two separate groups attempting to override environment for the
same nodes.

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Failed when searching for node
g4rlqrppmmi75av.delivery.puppetlabs.net: Classification of
g4rlqrppmmi75av.delivery.puppetlabs.net failed due to a classification
conflict: The node was classified into groups named "PE Certificate
Authority", "PE Console", "PE PuppetDB", "Production environment", "PE
ActiveMQ Broker", "PE Agent", "PE MCollective", "Special Environment",
and "PE Master" that defined conflicting values for the environment.

(In this case the conflict was between the groups "Production
environment" and "Special Environment" created by the test)

The fix was to get the new "Production environment"'s uuid and have it
be the parent of the test groups being created.